angular.module("directives",[])
        .directive("menu",function(){
            return{
                restrict:"A",
                templateUrl:"tpl/menu.html",
                link:function(a){
                    a.menu=[
                        {
                            title:"function",
                            son:[
                                {title:"angular.bind"},
                                {title:"angular.bootstrap"}
                            ]
                        },
                        {
                            title:"directive",
                            son:[
                                {title:"a"},
                                {title:"form"}
                            ]
                        },
                        {
                            title:"object",
                            son:[
                                {title:"angular.version"}
                            ]
                        },
                        {
                            title:"type",
                            son:[
                                {title:"$cacheFactory.Cache"},
                                {title:"$compile.directive.Attributes"}
                            ]
                        }
                    ];

                    a.index=0;
                    a.change=function(index){
                        a.index=index;
                    }
                }
            }
        })